<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>CFip</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>True</UseWindowsForms>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="nodesCatch.Sample.SampleClientConfig.txt" />
    <None Remove="nodesCatch.Sample.SampleHttprequest.txt" />
    <EmbeddedResource Include="nodesCatch.Sample.SampleClientConfig.txt" LogicalName="nodesCatch.Sample.SampleClientConfig.txt" />
    <EmbeddedResource Include="nodesCatch.Sample.SampleHttprequest.txt" LogicalName="nodesCatch.Sample.SampleHttprequest.txt" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Core" />
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\libs\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="System.Web" />
    <Reference Include="System.Resources.Extensions">
      <HintPath>..\libs\System.Resources.Extensions.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>